### ISSUE TITLE
Stopping the timer on mobile in a certain way leaves the timer kind of "stuck"

### ISSUE THREAD

**Issue by tussosedan** [cs0x7f/cstimer#93]
It appears this happens when stopping the timer with a lot of touch contact, in the area of the result display. The time stops while highlighted like when starting a solve, and needs another tap to go back to normal. Trying to start another solve in the stuck state doesn't work. It's a minor issue, but it happens to me very often.

Please see the [video](https://photos.app.goo.gl/HbyWWyvUEsALc1vq9). Reproduced on two Android phones.

**Comment by jgouly** [comment]
This basically happens every time on two phones I've tried. Also start the timer, the timer gets stuck in the green state and I have to press twice to get it to start.

**Comment by cs0x7f** [comment]
Should be fixed in https://github.com/cs0x7f/cstimer/commit/ed54f667cded9a9ac45cd042d69de10e59bcef50

**Comment by tussosedan** [comment]
Still happens on /src

**Comment by cs0x7f** [comment]
> Still happens on /src

I tested on my android phone. Have you cleaned browser cache?

**Comment by tussosedan** [comment]
Tried it now in private browsing, yes, still the same problem.

**Comment by cs0x7f** [comment]
> 
> 
> Tried it now in private browsing, yes, still the same problem.

I cannot reproduce the bug on my phone. Will the bug occur if you touch on left of the digits? According to my test, the bug only occurred when touching on the narowed digits.

**Comment by cs0x7f** [comment]
Well, I've reproduced the bug, with 4 of my fingers. I'll try to find out why this happens and whether it can be fixed.
